#!/bin/bash

#docker commands that I learn 

#to check docker hello world image and verify your docker stepup use this command 

docker run hello-wolrd

#want to the check the image is downloaded

docker images 

# to watch running containers 

docker ps 

#to watch all conatiners (including existed one )

docker ps -a

# to pull an image 

docker pull <image name >


#to remove a container 

docker rm <container id >

# to start a container 
docker start < container id  >

#to stop a container
docker stop  <conatianer id >

#to start a container 
docker run -d -p 8080:80 nginx

#-d _ runs it in the background 

#-p _ 8080:80 maps the host port 8080 to conatiners port 80 

#nginx -- tells docker to use the official image of nginx .





